# Generated by Django 3.2.6 on 2023-01-18 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230117_0921'),
        ('services', '0002_bookappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookappointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
