# Generated by Django 3.2.6 on 2023-01-18 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230117_0921'),
        ('services', '0003_auto_20230118_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceupload',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='accounts.serviceprovider'),
        ),
    ]
