# Generated by Django 4.1.3 on 2023-02-10 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customer_user"),
        ("services", "0005_auto_20230119_1129"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookappointment",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to="accounts.customer",
            ),
        ),
    ]
