# Generated by Django 4.1.3 on 2023-02-10 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customer_user"),
        ("services", "0006_alter_bookappointment_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookappointment",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_provider",
                to="accounts.serviceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="bookappointment",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service",
                to="services.service",
            ),
        ),
    ]
