# Generated by Django 3.2.6 on 2023-01-17 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_bookappointment'),
        ('accounts', '0002_customerprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerProfile',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='ServiceProviderProfile',
            new_name='ServiceProvider',
        ),
    ]
