# Generated by Django 4.1.3 on 2023-02-10 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customer_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceprovider",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_provider",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
